server:
  port: 8885
spring:
  application:
    name: evshang-gateway
  profiles:
    active: dev
  #zipkin:

# 标识该服务为注册中心
eureka:
  client:
    serviceUrl:
        prefer-ip-address: true
        defaultZone: http://localhost:8000/eureka/
#这个版本的需要手动开启熔断服务
feign:
  hystrix:
    enabled: true



security:
  basic:
    enabled: false
  oauth2:
    resource:
      user-info-uri: http://localhost:8010/user
      prefer-token-info: false

exclude:
  excludeUrls:
    - /auth/**



management:
  security:
    enabled: false

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    auth:
      path: /auth/**
      strip-prefix: true
      serviceId: evshang-authentication-service
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
