server:
  port: 8883
spring:
  application:
    name: evshang-gateway
  profiles:
    active: dev
# 标识该服务为注册中心
eureka:
  client:
    serviceUrl:
        prefer-ip-address: true
        defaultZone: http://localhost:8000/eureka/
#这个版本的需要手动开启熔断服务
feign:
  hystrix:
    enabled: true



security:
  basic:
    enabled: false
  oauth2:
    resource:
      token-info-uri: http://localhost:8333/user
      prefer-token-info: false

exclude:
  excludeUrls:
    - /auth/**



zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    auth:
      path: /auth/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: evshang-authentication-service
proxy:
  auth:
    routes:
      custom: oauth2

