server:
  port: 8885
spring:
  application:
    name: evshang-gateway
  profiles:
    active: dev
  redis:
    password: 123456
  zipkin:
    base-url: http://localhost:9998


# 标识该服务为注册中心
eureka:
  client:
    serviceUrl:
        prefer-ip-address: true
        defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true
#这个版本的需要手动开启熔断服务
feign:
  hystrix:
    enabled: true


security:
  basic:
    enabled: false
  oauth2:
    resource:
      loadBalanced: true
      user-info-uri: http://evshang-authentication-service/user
      prefer-token-info: false
      service-id: evshang-gateway

management:
  security:
    enabled: false

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    user:
      path: /api/user/**
      service-id: evshang-user-service
    auth:
      path: /auth/**
      sensitiveHeaders:
      service-id: evshang-authentication-service
  add-proxy-headers: true
  ignored-services: '*'
#排除的url,包括服务
exclude:
  exclude-urls:
    - /auth/**
    - /code/image
    - /loginCheck/form

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000