server:
  port: 8883
spring:
  application:
    name: evshang-gateway
  profiles:
    active: dev
# 标识该服务为注册中心
eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:8000/eureka/
zuul:
  routes:
    api: /user/**

