server:
  port: 8883
spring:
  application:
    name: evshang-gateway
  profiles:
    active: dev
# 标识该服务为注册中心
eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:8000/eureka/
#这个版本的需要手动开启熔断服务
feign:
  hystrix:
    enabled: true


security:
  oauth2:
    client:
      client-id: evshang
      client-secret: evshangsecret


zuul:
  ignored-patterns: /user/**/**
