server:
  port: 8885
spring:
  application:
    name: evshang-gateway
  profiles:
    active: dev
  redis:
    password: 123456
  zipkin:
    base-url: http://localhost:9998


# 标识该服务为注册中心
eureka:
  client:
    serviceUrl:
        prefer-ip-address: true
        defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true
#这个版本的需要手动开启熔断服务
feign:
  hystrix:
    enabled: true

evshang:
  security:
    oauth2:
      clients[0]:
        clientId: evshang
        client-secret: evshangsecret
      storyType: redis

# I don't think this configuration is recommended,Because this configuration is used,
#the address of the authentication server will be fixed and the cluster will not be able to be used, so this is very dangerous in the production environment.
#So I put the certification on the gateway
#security:
  #basic:
    #enabled: false
  #oauth2:
    #resource:
      #user-info-uri: http://localhost:8010/user
      #prefer-token-info: false


management:
  security:
    enabled: false

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    user:
      path: /api/user/**
      service-id: evshang-user-service


#排除的url,包括服务
exclude:
  exclude-urls:
    - /code/image
    - /loginCheck/form



hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000