server:
  port: 8010

eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:8000/eureka/
spring:
  application:
    name: evshang-authentication-service
  redis:
    password: 123456
    ssl: false
    host: localhost
    port: 6379



evshang:
  security:
    oauth2:
      clients[0]:
        clientId: evshang
        client-secret: evshangsecret
      storyType: jwt

