server:
  port: 9998
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: evshang-zipkin

spring:
  zipkin:
    enabled: false
